### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by g7dhaliwal** [cortner/NBodyIPs.jl#10]
Hi,

  I am trying to install this package using Pkg.clone(). I am getting the following error
ERROR: Compat `ASE` not listed in `deps` or `extras` section.

I have sepertely installed ASE package as well but still the error persists. Will really appreciate if you can help me with this issue.

Gurjot

**Comment by cortner** [comment]
This package hasn’t received a lot of attention recently. Before I advise you, 
- which version of Julia are you on?
- what are you planning to do with it?

**Comment by g7dhaliwal** [comment]
I am using version 1.3.0. We are developing IPs for multi-element species and wanted to check performance of this potential on our dataset.

**Comment by cortner** [comment]
Ok - it will take a lot of work to update this to 1.3. Instead try PoSH.jl

**Comment by g7dhaliwal** [comment]
Thanks for your suggestion and I will work with that package as well.

Your recent paper on arXiv got my interest in this package and I really wanted to test how it performed on my data. Can you please suggest the julia version that can help me in installation of NBodyIPs

**Comment by cortner** [comment]
I think 0.6.x ; but for multi-species you will need another package that we haven’t yet integrated - @dussong can you advise please?

**Comment by cortner** [comment]
FWIW it took us quite a bit of fiddling to get decent performance. And there are limitations - it is very difficult to go beyond 5-body interaction. This is much easier with PoSH.jl

**Comment by cortner** [comment]
For many species - say 4 or more we think APIPs (this package) will be more performant. But there is quite a bit of work to get it up to the same level as PoSH.jl

**Comment by g7dhaliwal** [comment]
Thanks.

I am following the example provided. On running the following command, I got the error

data = NBodyIPs.Data.read(path)

Error:- ERROR: UndefVarError: Data not defined

**Comment by cortner** [comment]
Please wait for Geneviève to send you the relevant package names and versions

**Comment by cortner** [comment]
@dussong since our paper is out soon should we make the multispecies Version public?

**Comment by dussong** [comment]
Yes, the package for multi-species systems is called NBIPsMulti, but is still private. It still needs a bit of cleaning and commenting before I make it public.

**Comment by g7dhaliwal** [comment]
Thanks for your comments. Can you please help me with the error mentioned above?
I think it is missing data.jl file.

**Comment by cortner** [comment]
@dussong Let's discuss this next time we meet.

@g7dhaliwal I'm afraid it is a lot more complicated than that. We have to think about how to make this accessible - if at all.

**Comment by g7dhaliwal** [comment]
Thanks for your comments. I will wait for your multi-body package. I know you must be super busy with projects at hand but if you can give me an estimate date for release, that will be helpful.

Meanwhile, if you can fix the issues with "NBodyIP" package that will be really great. I have dataset for single elemental species as well and was interested in performace anlysis of your code against that data.

**Comment by cortner** [comment]
It is unlikely we will update either package in the near future to Julia 1.x. All you need are the correct version numbers of the surrounding packages. @dussong - do you still have these stored somewhere? A simple `Pkg.status()` should give you that if you have a system installed that can still run this package.

**Comment by cortner** [comment]
@g7dhaliwal I'm just not sure why you want this code at all. I already mentioned to you our new package `PoSH.jl` which is much more performant (at least for elemental materials) and more general as well. If you tell us what you are really after then we can better help you.

What I do not want to see is our package being used in a benchmark without one of us involved in generating the results.

**Comment by g7dhaliwal** [comment]
Thanks. I will use PoSH.jl.
