### ISSUE TITLE
IO Interface

### ISSUE THREAD

**Issue by cortner** [cortner/NBodyIPs.jl#4]
CC @casv2 

How should the IP be stored on disk: we need to save 
 - the tuples representing the basis functions
 - the coefficients 
 - the space transform 
 - the cut-off mechanism
 - name of the dataset(s) the .jld file was fitted on
 - complete set of fitting parameters / settings.
 - the `NBodyIPs.jl` and `NBodyIPFitting.jl` git hash?
 - it may in fact be easiest to just store the entire source code of the script use for fitting? But then we'd also need the source code that generated the LsqDB? Not too sure about this one.

**Comment by cortner** [comment]
@gabor1 @casv2 Following a recent request from Gabor, I want to clean up how I store `IPs`. Can you please look through the list above and add anything you'd like me to add here? E.g. another things that comes to mind: 
* table of fitting errors.

**Comment by casv2** [comment]
I think "e0" should be stored in there too

**Comment by cortner** [comment]
this should all be implemented and working on the current `master`
